artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/Durgeshsingh12712/Data-All/refs/heads/main/Unified%20Dataset/youtube_channel_real_performance_analytics.csv
  local_data_file: artifacts/data_ingestion/data.csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  required_files:
    - data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  preprocessor_obj_file_path: artifacts/data_transformation/preprocessor.pkl
  transformed_train_file_path: artifacts/data_transformation/train.csv
  transformed_test_file_path: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.pkl
  all_params: params.yaml
  metric_file_name: artifacts/model_evaluation/metrics.json
  target_column: 'Estimated Revenue (USD)'